# Generated by Django 5.1.2 on 2024-10-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='mix_speed',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
